# Generated by Django 5.2.7 on 2025-10-16 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="todos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[("Low", "Low"), ("Medium", "Medium"), ("High", "High")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="title",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
